-- =============================================================================
-- DataFlow Observatory — Snowflake Setup
-- Run via:  python3 snowflake/run_setup.py
-- =============================================================================

-- ── Warehouse ─────────────────────────────────────────────────────────────────
CREATE WAREHOUSE IF NOT EXISTS DFO_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    COMMENT        = 'DataFlow Observatory compute warehouse';

USE WAREHOUSE DFO_WH;

-- ── Database ──────────────────────────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS DATAFLOW_OBSERVATORY
    COMMENT = 'DataFlow Observatory — all schemas live here';

USE DATABASE DATAFLOW_OBSERVATORY;

-- ── Schemas ───────────────────────────────────────────────────────────────────
-- RAW      : landing zone for Kafka payloads (written by loader.py)
-- STAGING  : dbt views that extract from VARIANT columns
-- ANALYTICS: dbt incremental tables (fct_events, dq_metrics, alert_summary)

CREATE SCHEMA IF NOT EXISTS RAW
    COMMENT = 'Raw semi-structured payloads loaded from Kafka';

CREATE SCHEMA IF NOT EXISTS STAGING
    COMMENT = 'dbt staging views';

CREATE SCHEMA IF NOT EXISTS ANALYTICS
    COMMENT = 'dbt mart tables powering Grafana';

USE SCHEMA RAW;

-- ── RAW.EVENTS ────────────────────────────────────────────────────────────────
-- One row per Kafka message from the raw_events topic.
-- Top-level columns are extracted for clustering; full JSON lives in PAYLOAD.
CREATE TABLE IF NOT EXISTS RAW.EVENTS (
    EVENT_ID   VARCHAR(36)    NOT NULL COMMENT 'UUID from the simulator',
    SOURCE     VARCHAR(50)    NOT NULL COMMENT 'clickstream | iot_sensor',
    LOADED_AT  TIMESTAMP_TZ   NOT NULL DEFAULT CURRENT_TIMESTAMP()
                              COMMENT 'Wall-clock time this row landed in Snowflake',
    PAYLOAD    VARIANT        NOT NULL COMMENT 'Full JSON event',

    CONSTRAINT PK_EVENTS PRIMARY KEY (EVENT_ID)
)
CLUSTER BY (DATE_TRUNC('HOUR', LOADED_AT), SOURCE)
COMMENT = 'Raw events from all Kafka sources';

-- ── RAW.QUALITY_ALERTS ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS RAW.QUALITY_ALERTS (
    ALERT_ID   VARCHAR(36)    NOT NULL COMMENT 'UUID generated by the validator',
    SOURCE     VARCHAR(50)             COMMENT 'Event source that triggered the alert',
    SEVERITY   VARCHAR(20)             COMMENT 'low | medium | high | critical',
    LOADED_AT  TIMESTAMP_TZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PAYLOAD    VARIANT        NOT NULL COMMENT 'Full QualityAlert JSON',

    CONSTRAINT PK_QUALITY_ALERTS PRIMARY KEY (ALERT_ID)
)
CLUSTER BY (DATE_TRUNC('HOUR', LOADED_AT), SOURCE, SEVERITY)
COMMENT = 'Quality alerts produced by the Go validator';

-- ── Verify ────────────────────────────────────────────────────────────────────
SHOW TABLES IN SCHEMA RAW;
SHOW SCHEMAS IN DATABASE DATAFLOW_OBSERVATORY;
